apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-nakamura-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d11e9bca-137d-4915-9d69-5e8ab142d832
    keyvaultName: nakamura-kv                 
    cloudName: ""
    objects: |
      array:
        - |
          objectName: MSSQL-SA-PASSWORD
          objectType: secret
          objectVersion: "" 
        - |
          objectName: AZURE-SPEECHSERVICES-APIKEY
          objectType: secret
          objectVersion: "" 
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
          objectVersion: "" 
    tenantId: 9dc188b2-8f44-49de-8846-453d54fc1eae
  secretObjects:
  - data:
    - key: MSSQL-SA-PASSWORD
      objectName: MSSQL-SA-PASSWORD
    - key: AZURE-SPEECHSERVICES-APIKEY
      objectName: AZURE-SPEECHSERVICES-APIKEY
    - key: OPENAI-API-KEY
      objectName: OPENAI-API-KEY
    secretName: azure-nakamura-kv
    type: Opaque
